### PR TITLE
add vision_board_tinyusb_xpad for usb host demo

### PR DESCRIPTION
**Pull request by KunYi**
the project for USBFS Host demo
only support XBoxOne Controller (VID:045e, PID:0b12)

### CODE REVIEW

**Comment by Rbb666** [comment]
Thanks you PR,you can refer to this script to link tinyusb to the project instead of adding the tinyusb source code to packages.：https://github.com/RT-Thread-Studio/sdk-bsp-ra8d1-vision-board/blob/12b10dcbf0f5707ebde62ef05beab269a6c80fac/projects/usb/vision_board_tinyusb/SConstruct#L90

**Comment by Rbb666** [comment]
You also need to add the project to CI:https://github.com/RT-Thread-Studio/sdk-bsp-ra8d1-vision-board/blob/12b10dcbf0f5707ebde62ef05beab269a6c80fac/.github/workflows/action.yml#L68

**Comment by KunYi** [comment]
the original 'libraries/components/tinyusb' only for device configuration, so I fork a new customization tinyusb under packages

**Comment by Rbb666** [comment]
> the original 'libraries/components/tinyusb' only for device configuration, so I fork a new customization tinyusb under packages

The tinyusb and libraries/components/tinyusb under packages are redundant, which will cause the repo to much larger. Can the tinyusb under libraries/components not be used?

**Comment by KunYi** [comment]
cannot work with  libraries/components/tinyusb now
need do more work to re-factory the package and add some configuration by Kconfig and modify platform adaption layer  to support host
the RT-thread default code only support device

**Comment by Rbb666** [comment]
> 无法与库/组件/tinyusb 一起使用，现在需要做更多的工作来重新制作软件包，并通过 Kconfig 添加一些配置，并修改平台适配层以支持托管 RT-thread 默认代码仅支持设备



> 无法与库/组件/tinyusb 一起使用，现在需要做更多的工作来重新制作软件包，并通过 Kconfig 添加一些配置，并修改平台适配层以支持托管 RT-thread 默认代码仅支持设备

You can write these configurations to board/kconfig, similar to this demo:https://github.com/RT-Thread-Studio/sdk-bsp-ra8d1-vision-board/blob/12b10dcbf0f5707ebde62ef05beab269a6c80fac/projects/usb/vision_board_tinyusb_uvc/board/Kconfig#L587

**Pull request closed without merging**
